<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bc364056-5850-4b25-89ba-7cf953bc0692</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\Analysis.Data\Analysis.Data.csproj" />
  </ItemGroup>

</Project>
