// <auto-generated />
using System;
using InnovaFlow.Analysis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analysis.Data.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20260830075641_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Analysis")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InnovaFlow.Analysis.Data.AIRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("AIRequests", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdeaVersionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.HasIndex("IdeaVersionId");

                    b.HasIndex("IdeaId", "StartedAt")
                        .HasDatabaseName("IX_Analyses_IdeaId_StartedAt");

                    b.ToTable("Analyses", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.AnalysisScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId", "ScoreType")
                        .IsUnique();

                    b.ToTable("AnalysisScores", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.AudienceAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryAudience")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryAudience")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("AudienceAnalyses", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.BrandAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommunicationStyle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<string>("CoreValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("NameSuggestions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Positioning")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<string>("Slogans")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("VisualIdentity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("BrandAnalyses", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.BusinessAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessModel")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CostAnalysis")
                        .HasColumnType("text");

                    b.Property<string>("PricingStrategy")
                        .HasColumnType("text");

                    b.Property<string>("RevenueModel")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("RevenuePotential")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("BusinessAnalyses", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Competitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PricingModel")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("SimilarityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.PrimitiveCollection<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("Competitors", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.FeasibilityAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ComplexityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("ResourceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<decimal?>("TechnicalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("FeasibilityAnalyses", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.MarketAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("MarketOpportunity")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("MarketSize")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MarketTrend")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("MarketAnalyses", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OpportunityAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("PotentialImpact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityAnalysisId");

                    b.ToTable("Opportunities", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.OpportunityAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OpportunityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("OpportunityAnalyses", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgeRange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("AudienceAnalysisId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Behaviors")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("Goals")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.PrimitiveCollection<string>("PainPoints")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AudienceAnalysisId");

                    b.ToTable("Personas", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("Recommendations", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("Impact")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Mitigation")
                        .HasColumnType("text");

                    b.Property<decimal?>("Probability")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("RiskAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RiskAnalysisId");

                    b.HasIndex("RiskAnalysisId", "Severity");

                    b.ToTable("Risks", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.RiskAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("RiskAnalyses", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RelevanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("Sources", "Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.AIRequest", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany("Requests")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.AnalysisScore", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany("Scores")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.AudienceAnalysis", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.BrandAnalysis", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.BusinessAnalysis", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Competitor", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.FeasibilityAnalysis", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.MarketAnalysis", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Opportunity", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.OpportunityAnalysis", "OpportunityAnalysis")
                        .WithMany("Opportunities")
                        .HasForeignKey("OpportunityAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpportunityAnalysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.OpportunityAnalysis", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Persona", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.AudienceAnalysis", "AudienceAnalysis")
                        .WithMany("Personas")
                        .HasForeignKey("AudienceAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudienceAnalysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Recommendation", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany("Recommendations")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Risk", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.RiskAnalysis", "RiskAnalysis")
                        .WithMany("Risks")
                        .HasForeignKey("RiskAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskAnalysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.RiskAnalysis", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Source", b =>
                {
                    b.HasOne("InnovaFlow.Analysis.Data.Analysis", "Analysis")
                        .WithMany("Sources")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.Analysis", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("Requests");

                    b.Navigation("Scores");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.AudienceAnalysis", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.OpportunityAnalysis", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("InnovaFlow.Analysis.Data.RiskAnalysis", b =>
                {
                    b.Navigation("Risks");
                });
#pragma warning restore 612, 618
        }
    }
}
